import type { Contact, Deal, Activity, AIInsight } from "./types";

export const contacts: Contact[] = [
  {
    id: "c1",
    name: "Sarah Mitchell",
    email: "sarah.mitchell@techcorp.com",
    phone: "+1 (555) 234-5678",
    company: "TechCorp Inc.",
    title: "VP of Engineering",
    status: "prospect",
    leadScore: 87,
    sentiment: "positive",
    tags: ["enterprise", "warm"],
    lastActivity: "2026-08-28T10:00:00Z",
    createdAt: "2026-07-15T00:00:00Z",
    notes: "Very interested in the enterprise plan. Follow up after demo.",
  },
  {
    id: "c2",
    name: "James Okafor",
    email: "james.okafor@fintech.io",
    phone: "+1 (555) 345-6789",
    company: "FinTech IO",
    title: "CEO",
    status: "customer",
    leadScore: 95,
    sentiment: "positive",
    tags: ["enterprise", "vip"],
    lastActivity: "2026-08-29T14:30:00Z",
    createdAt: "2026-05-10T00:00:00Z",
    notes: "Long-term customer. Upsell opportunity for new analytics module.",
  },
  {
    id: "c3",
    name: "Priya Sharma",
    email: "priya.sharma@startupxyz.com",
    phone: "+1 (555) 456-7890",
    company: "StartupXYZ",
    title: "CTO",
    status: "lead",
    leadScore: 62,
    sentiment: "neutral",
    tags: ["startup", "tech"],
    lastActivity: "2026-08-25T09:00:00Z",
    createdAt: "2026-08-20T00:00:00Z",
    notes: "Downloaded whitepaper. Needs nurturing.",
  },
  {
    id: "c4",
    name: "Marcus Thompson",
    email: "marcus.t@retailgiant.com",
    phone: "+1 (555) 567-8901",
    company: "Retail Giant",
    title: "Director of Operations",
    status: "prospect",
    leadScore: 74,
    sentiment: "positive",
    tags: ["retail", "mid-market"],
    lastActivity: "2026-08-27T11:00:00Z",
    createdAt: "2026-08-01T00:00:00Z",
    notes: "Attended webinar. Requested pricing info.",
  },
  {
    id: "c5",
    name: "Elena Vasquez",
    email: "elena.v@healthtech.org",
    phone: "+1 (555) 678-9012",
    company: "HealthTech Org",
    title: "Product Manager",
    status: "lead",
    leadScore: 45,
    sentiment: "neutral",
    tags: ["healthcare", "smb"],
    lastActivity: "2026-08-20T15:00:00Z",
    createdAt: "2026-08-18T00:00:00Z",
    notes: "Cold lead from conference.",
  },
  {
    id: "c6",
    name: "David Chen",
    email: "dchen@globallogistics.net",
    phone: "+1 (555) 789-0123",
    company: "Global Logistics",
    title: "COO",
    status: "customer",
    leadScore: 91,
    sentiment: "positive",
    tags: ["enterprise", "logistics"],
    lastActivity: "2026-08-30T08:00:00Z",
    createdAt: "2026-03-22T00:00:00Z",
    notes: "Renewal due next quarter. Strong advocate.",
  },
  {
    id: "c7",
    name: "Amara Nwosu",
    email: "amara.n@eduplatform.edu",
    phone: "+1 (555) 890-1234",
    company: "EduPlatform",
    title: "Head of Technology",
    status: "churned",
    leadScore: 28,
    sentiment: "negative",
    tags: ["education", "at-risk"],
    lastActivity: "2026-07-10T10:00:00Z",
    createdAt: "2025-11-15T00:00:00Z",
    notes: "Churned due to budget cuts. Re-engage in Q4.",
  },
  {
    id: "c8",
    name: "Ryan Park",
    email: "ryan.park@cloudsolutions.co",
    phone: "+1 (555) 901-2345",
    company: "Cloud Solutions Co.",
    title: "Sales Engineer",
    status: "prospect",
    leadScore: 68,
    sentiment: "positive",
    tags: ["cloud", "tech"],
    lastActivity: "2026-08-28T16:00:00Z",
    createdAt: "2026-08-10T00:00:00Z",
    notes: "Evaluating competitors. Demo scheduled.",
  },
];

export const deals: Deal[] = [
  {
    id: "d1",
    title: "TechCorp Enterprise License",
    contactId: "c1",
    contactName: "Sarah Mitchell",
    company: "TechCorp Inc.",
    value: 125000,
    stage: "proposal",
    probability: 65,
    aiProbability: 72,
    expectedCloseDate: "2026-09-30T00:00:00Z",
    createdAt: "2026-07-20T00:00:00Z",
    notes: "Proposal sent. Awaiting feedback from board.",
    tags: ["enterprise", "priority"],
  },
  {
    id: "d2",
    title: "FinTech IO Analytics Upsell",
    contactId: "c2",
    contactName: "James Okafor",
    company: "FinTech IO",
    value: 48000,
    stage: "negotiation",
    probability: 85,
    aiProbability: 91,
    expectedCloseDate: "2026-09-15T00:00:00Z",
    createdAt: "2026-08-01T00:00:00Z",
    notes: "In final negotiation. Very likely to close.",
    tags: ["upsell", "analytics"],
  },
  {
    id: "d3",
    title: "StartupXYZ Starter Plan",
    contactId: "c3",
    contactName: "Priya Sharma",
    company: "StartupXYZ",
    value: 9600,
    stage: "qualification",
    probability: 40,
    aiProbability: 38,
    expectedCloseDate: "2026-10-31T00:00:00Z",
    createdAt: "2026-08-22T00:00:00Z",
    notes: "Still qualifying needs. Budget unknown.",
    tags: ["startup"],
  },
  {
    id: "d4",
    title: "Retail Giant Operations Suite",
    contactId: "c4",
    contactName: "Marcus Thompson",
    company: "Retail Giant",
    value: 72000,
    stage: "prospecting",
    probability: 30,
    aiProbability: 35,
    expectedCloseDate: "2026-11-30T00:00:00Z",
    createdAt: "2026-08-05T00:00:00Z",
    notes: "Early stage. Pricing deck requested.",
    tags: ["retail"],
  },
  {
    id: "d5",
    title: "Global Logistics Renewal",
    contactId: "c6",
    contactName: "David Chen",
    company: "Global Logistics",
    value: 156000,
    stage: "closed_won",
    probability: 100,
    aiProbability: 100,
    expectedCloseDate: "2026-08-15T00:00:00Z",
    createdAt: "2026-07-01T00:00:00Z",
    notes: "Renewed for 2 years. Excellent relationship.",
    tags: ["renewal", "enterprise"],
  },
  {
    id: "d6",
    title: "Cloud Solutions Pro Plan",
    contactId: "c8",
    contactName: "Ryan Park",
    company: "Cloud Solutions Co.",
    value: 24000,
    stage: "qualification",
    probability: 50,
    aiProbability: 55,
    expectedCloseDate: "2026-10-15T00:00:00Z",
    createdAt: "2026-08-12T00:00:00Z",
    notes: "Competing with two other vendors.",
    tags: ["cloud"],
  },
  {
    id: "d7",
    title: "HealthTech Pilot Program",
    contactId: "c5",
    contactName: "Elena Vasquez",
    company: "HealthTech Org",
    value: 6000,
    stage: "prospecting",
    probability: 20,
    aiProbability: 18,
    expectedCloseDate: "2026-12-31T00:00:00Z",
    createdAt: "2026-08-19T00:00:00Z",
    notes: "Budget approval needed.",
    tags: ["healthcare", "pilot"],
  },
  {
    id: "d8",
    title: "EduPlatform Re-engagement",
    contactId: "c7",
    contactName: "Amara Nwosu",
    company: "EduPlatform",
    value: 14400,
    stage: "closed_lost",
    probability: 0,
    aiProbability: 0,
    expectedCloseDate: "2026-07-30T00:00:00Z",
    createdAt: "2026-06-15T00:00:00Z",
    notes: "Budget constraints cited. Try again in Q4.",
    tags: ["education"],
  },
];

export const activities: Activity[] = [
  {
    id: "a1",
    type: "call",
    title: "Discovery call with Sarah Mitchell",
    description:
      "Discussed pain points around scalability. Very receptive. Next step: send proposal.",
    contactId: "c1",
    contactName: "Sarah Mitchell",
    dealId: "d1",
    dealTitle: "TechCorp Enterprise License",
    date: "2026-08-28T10:00:00Z",
    completed: true,
    sentiment: "positive",
    aiSummary:
      "Contact expressed strong interest in scalability features. High purchase intent detected.",
  },
  {
    id: "a2",
    type: "email",
    title: "Follow-up email to James Okafor",
    description: "Sent updated pricing for analytics module.",
    contactId: "c2",
    contactName: "James Okafor",
    dealId: "d2",
    dealTitle: "FinTech IO Analytics Upsell",
    date: "2026-08-29T14:30:00Z",
    completed: true,
    sentiment: "positive",
    aiSummary:
      "Positive response expected. Email tone analysis shows strong relationship.",
  },
  {
    id: "a3",
    type: "meeting",
    title: "Product demo for Ryan Park",
    description: "Scheduled product walkthrough for Cloud Solutions team.",
    contactId: "c8",
    contactName: "Ryan Park",
    dealId: "d6",
    dealTitle: "Cloud Solutions Pro Plan",
    date: "2026-08-31T14:00:00Z",
    completed: false,
    sentiment: "neutral",
    aiSummary:
      "Competitor evaluation in progress. Focus on unique differentiators during demo.",
  },
  {
    id: "a4",
    type: "task",
    title: "Prepare proposal for Marcus Thompson",
    description: "Create custom pricing proposal for Retail Giant.",
    contactId: "c4",
    contactName: "Marcus Thompson",
    dealId: "d4",
    dealTitle: "Retail Giant Operations Suite",
    date: "2026-09-01T09:00:00Z",
    completed: false,
  },
  {
    id: "a5",
    type: "note",
    title: "Conference notes - Elena Vasquez",
    description: "Met at HealthTech summit. Interested in compliance features.",
    contactId: "c5",
    contactName: "Elena Vasquez",
    date: "2026-08-20T15:00:00Z",
    completed: true,
    sentiment: "neutral",
  },
  {
    id: "a6",
    type: "call",
    title: "Renewal discussion with David Chen",
    description:
      "Confirmed 2-year renewal. Very satisfied with the platform performance.",
    contactId: "c6",
    contactName: "David Chen",
    dealId: "d5",
    dealTitle: "Global Logistics Renewal",
    date: "2026-08-30T08:00:00Z",
    completed: true,
    sentiment: "positive",
    aiSummary:
      "Extremely positive sentiment. Strong candidate for referral program.",
  },
  {
    id: "a7",
    type: "email",
    title: "Re-engagement email to Amara Nwosu",
    description: "Sent Q4 budget planning resources.",
    contactId: "c7",
    contactName: "Amara Nwosu",
    date: "2026-09-02T10:00:00Z",
    completed: false,
    sentiment: "neutral",
  },
  {
    id: "a8",
    type: "meeting",
    title: "Quarterly review with James Okafor",
    description: "Schedule QBR for FinTech IO account.",
    contactId: "c2",
    contactName: "James Okafor",
    date: "2026-09-05T11:00:00Z",
    completed: false,
  },
];

export const aiInsights: AIInsight[] = [
  {
    id: "i1",
    type: "alert",
    title: "High-value deal at risk of stalling",
    description:
      'The "TechCorp Enterprise License" deal ($125K) has not progressed in 10 days. Consider scheduling a follow-up call with Sarah Mitchell to re-engage.',
    priority: "high",
    relatedContactId: "c1",
    relatedDealId: "d1",
    createdAt: "2026-08-30T06:00:00Z",
  },
  {
    id: "i2",
    type: "recommendation",
    title: "Upsell opportunity detected",
    description:
      "James Okafor's usage patterns suggest he could benefit from the Premium Analytics add-on. His current plan is at 87% capacity.",
    priority: "high",
    relatedContactId: "c2",
    relatedDealId: "d2",
    createdAt: "2026-08-30T06:00:00Z",
  },
  {
    id: "i3",
    type: "prediction",
    title: "FinTech IO deal likely to close this week",
    description:
      "Based on engagement history and negotiation stage, there is a 91% probability of closing the $48K FinTech IO deal within the next 7 days.",
    priority: "high",
    relatedContactId: "c2",
    relatedDealId: "d2",
    createdAt: "2026-08-30T06:00:00Z",
  },
  {
    id: "i4",
    type: "recommendation",
    title: "Re-engage churned customer",
    description:
      "Amara Nwosu from EduPlatform churned 7 weeks ago. Q4 budget planning season is approaching — now is an ideal time to reconnect with a new offer.",
    priority: "medium",
    relatedContactId: "c7",
    createdAt: "2026-08-30T06:00:00Z",
  },
  {
    id: "i5",
    type: "alert",
    title: "Low engagement from new leads",
    description:
      "Priya Sharma and Elena Vasquez have had minimal interactions. Automated nurture sequences are recommended to keep them warm.",
    priority: "medium",
    relatedContactId: "c3",
    createdAt: "2026-08-30T06:00:00Z",
  },
  {
    id: "i6",
    type: "prediction",
    title: "Pipeline revenue forecast",
    description:
      "AI models forecast $198K in deal closures for September based on current pipeline stage distributions and historical close rates.",
    priority: "low",
    createdAt: "2026-08-30T06:00:00Z",
  },
];
